module.exports = {
    "-KOBxPpMqTZA_hUK04Ox": {
        "bodies": [ "They are Johnson & Johnson (NYSE: JNJ), Microsoft (Nasdaq: MSFT) and Exxon Mobil (NYSE: XOM). They represent the strongest balance sheets in the land.", "Meanwhile Chevron (CVX) and Exxon Mobil (XOM) – paying 5% and 3.9% respectively – are, to their credit, making money. But Chevron's payout ratio has ...", "(NYSE: XOM) process several hundreds of thousands of barrels per day. Proximity to refineries is a factor in gasoline prices, if the refineries are running at or ...", "XOM -3.47 % It is by most standards massive, having rivaled Apple for the global market-value crown before the latest commodity swoon. But its proven reserves ...", "For years, there has been a steady drumbeat of surveys that tell us we aren't saving enough. Bankrate.com's latest look at how people handle their money found ...", "I pay little attention to analysts' stock ratings because their recommendations are almost always to buy or hold a particular stock. Analysts had 11,539 stock ...", "Cecile Richards, president of Planned Parenthood Federation of America and the Planned Parenthood Action Fund, will deliver the keynote address April 4 at ...", "Europa es el continente perfecto para que las startups nazcan y se desarrollen en un entorno internacional. Contrariamente a otros lugares como los Estados ...", "A estas alturas de la historia, todos deberíamos saber de sobras que no hay ningún sitio en el que nos encontremos seguros al 100%. Se pueden dar diferentes ...", "Bộ phim xoay quanh câu chuyện về 5 người bạn thân trong xom là Duk Sun, Jung Hwan, Choi Taek, Sun Woo và Dong Ryung. Họ cùng trải qua tuổi thơ bên ..." ],
        "date": "1/10/2016",
        "headlines": [ "A Terrible Start: Three Ultra-Safe Stocks for a Market Bust", "Where To Find Secure 7.6% Yields In 2016", "Gas prices could drop toward $1 a gallon", "Saudi Aramco: Bigger Oil, Bigger Trouble", "Michelle Singletary: Financial fast can help make saving a habit", "Will Deener: If analysts say to 'sell' a stock, then buy", "Cecile Richards to speak at Dallas Planned Parenthood event", "¿Cuál es el secreto de las startups en Europa?", "Habitaciones seguras, miedo, y los límites del pensamiento irracional", "Phim \"Reply 1988\" Hàn Quốc được quay tại nhà cố Tổng thống" ],
        "symbol": "XOM"

    }

};